apiVersion: v1
kind: Service
metadata:
  name: springboot-microservice
spec:
  type: ClusterIP
  selector:
    app: springboot-microservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
